export const APPEND_REVIEWS = "APP/REVIEWS/APPEND_REVIEWS";
export const INCREMENT_PAGE = "APP/REVIEWS/INCREMENT_PAGE";
export const RESET_PAGE = "APP/REVIEWS/INCREMENT_PAGE";
export const SET_ERROR = "APP/REVIEWS/SET_ERROR";
export const SET_FILTERED_REVIEWS = "APP/REVIEWS/SET_FILTERED_REVIEWS";
export const SET_LOADING = "APP/REVIEWS/SET_LOADING";
export const SET_REVIEWS = "APP/REVIEWS/SET_REVIEWS";
